# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledata',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='retailer_id',
            new_name='retailer',
        ),
    ]
